export enum DroughtSpecific {
  NumVillAff = 'NumVillAff',
  NumFamAff = 'NumFamAff',
  NumPeoAff = 'NumPeoAff',
  NumMe = 'NumMe',
  NumFe = 'NumFe',
  NumKid = 'NumKid',
  NumOld = 'NumOld',
  NumDisMising = 'NumDisMising',
  TNumDeath = 'TNumDeath',
  NumMeDeath = 'NumMeDeath',
  NumFeDeath = 'NumFeDeath',
  NumKidDeath = 'NumKidDeath',
  NumOldDeath = 'NumOldDeath',
  NumDisDeath = 'NumDisDeath',
  FamAgriAff = 'FamAgriAff',
  FarmAff = 'FarmAff',
  FarmDam = 'FarmDam',
  SamNabAff = 'SamNabAff',
  SamNabDam = 'SamNabDam',
  PaddyAff = 'PaddyAff',
  PaddyDam = 'PaddyDam',
  CowDeath = 'CowDeath',
  BaffoDeath = 'BaffoDeath',
  PigDeath = 'PigDeath',
  BirdDeath = 'BirdDeath',
  NumSchNoHo2 = 'NumSchNoHo2',
  BotSourTang = 'BotSourTang',
  HSourNoTang = 'HSourNoTang',
  NoSourHtang = 'NoSourHtang',
  NoBtSourTan = 'NoBtSourTan',
  Electric = 'Electric',
  HealCenNoHo2 = 'HealCenNoHo2',
  HBotSourTang = 'HBotSourTang',
  HaSouNoTang = 'HaSouNoTang',
  NoSourHatan = 'NoSourHatan',
  NoBtSouTan = 'NoBtSouTan',
  ElecForHeal = 'ElecForHeal',
  DamHavWater = 'DamHavWater',
  DamNoWater = 'DamNoWater',
  PondHavWat = 'PondHavWat',
  PondNoWate = 'PondNoWate',
  PlumWelHaWat = 'PlumWelHaWat',
  PluWelNoWat = 'PluWelNoWat',
  DigWelHaWat = 'DigWelHaWat',
  DigWelNoWat = 'DigWelNoWat',
  NuVilNedHep = 'NuVilNedHep',
  TNuFamNeHo2 = 'TNuFamNeHo2',
  NumPeople = 'NumPeople',
  NumMen = 'NumMen',
  NumWomen = 'NumWomen',
  NumKids = 'NumKids',
  NumElder = 'NumElder',
  NumDis = 'NumDis',
  NumWatTank = 'NumWatTank',
  NuStorageFam = 'NuStorageFam',
  NumWateTank = 'NumWateTank',
  NumFilter = 'NumFilter',
  NumWatePur = 'NumWatePur',
  NumWatStor = 'NumWatStor',
  WatSorRepar = 'WatSorRepar',
  WatStoRepar = 'WatStoRepar',
  SolarNeed = 'SolarNeed',
  FanNeed = 'FanNeed',
  WatStorNed = 'WatStorNed',
  WatSorRep = 'WatSorRep',
  WatStoRep = 'WatStoRep',
  NuSolarNeed = 'NuSolarNeed',
  NumFanNeed = 'NumFanNeed',
  LandSize = 'LandSize',
  PumMachine = 'PumMachine',
  NumGasoline = 'NumGasoline',
  NumFam = 'NumFam',
  FamNoIncom = 'FamNoIncom',
  PeoNoIncom = 'PeoNoIncom',
  FamNoFod = 'FamNoFod',
  PeoNoFod = 'PeoNoFod',
  NuKidColWat = 'NuKidColWat',
  IfYes = 'IfYes',
  NuWoCollWat = 'NuWoCollWat',
  Yes = 'Yes',
  TreatOccur = 'TreatOccur',
}

export const droughtSpecificKeys = {
  [DroughtSpecific.NumVillAff]: 'group_dg01m69/NumVillAff',
  [DroughtSpecific.NumFamAff]: 'group_dg01m69/group_kx2wb92/NumFamAff',
  [DroughtSpecific.NumPeoAff]: 'group_dg01m69/group_kx2wb92/NumPeoAff',
  [DroughtSpecific.NumMe]: 'group_dg01m69/group_kx2wb92/NumMe',
  [DroughtSpecific.NumFe]: 'group_dg01m69/group_kx2wb92/NumFe',
  [DroughtSpecific.NumKid]: 'group_dg01m69/group_kx2wb92/NumKid',
  [DroughtSpecific.NumOld]: 'group_dg01m69/group_kx2wb92/NumOld',
  [DroughtSpecific.NumDisMising]: 'group_dg01m69/group_kx2wb92/NumDisMising',
  [DroughtSpecific.TNumDeath]: 'group_dg01m69/group_nk3zh15/TNumDeath',
  [DroughtSpecific.NumMeDeath]: 'group_dg01m69/group_nk3zh15/NumMeDeath',
  [DroughtSpecific.NumFeDeath]: 'group_dg01m69/group_nk3zh15/NumFeDeath',
  [DroughtSpecific.NumKidDeath]: 'group_dg01m69/group_nk3zh15/NumKidDeath',
  [DroughtSpecific.NumOldDeath]: 'group_dg01m69/group_nk3zh15/NumOldDeath',
  [DroughtSpecific.NumDisDeath]: 'group_dg01m69/group_nk3zh15/NumDisDeath',
  [DroughtSpecific.FamAgriAff]: 'group_yn34m57/group_rg2xt75/FamAgriAff',
  [DroughtSpecific.FarmAff]: 'group_yn34m57/group_rg2xt75/FarmAff',
  [DroughtSpecific.FarmDam]: 'group_yn34m57/group_rg2xt75/FarmDam',
  [DroughtSpecific.SamNabAff]: 'group_yn34m57/group_rg2xt75/SamNabAff',
  [DroughtSpecific.SamNabDam]: 'group_yn34m57/group_rg2xt75/SamNabDam',
  [DroughtSpecific.PaddyAff]: 'group_yn34m57/group_rg2xt75/PaddyAff',
  [DroughtSpecific.PaddyDam]: 'group_yn34m57/group_rg2xt75/PaddyDam',
  [DroughtSpecific.CowDeath]: 'group_yn34m57/group_pl5gf73/CowDeath',
  [DroughtSpecific.BaffoDeath]: 'group_yn34m57/group_pl5gf73/BaffoDeath',
  [DroughtSpecific.PigDeath]: 'group_yn34m57/group_pl5gf73/PigDeath',
  [DroughtSpecific.BirdDeath]: 'group_yn34m57/group_pl5gf73/BirdDeath',
  [DroughtSpecific.NumSchNoHo2]: 'group_em29q27/group_oh4fa74/NumSchNoHo2',
  [DroughtSpecific.BotSourTang]: 'group_em29q27/group_oh4fa74/BotSourTang',
  [DroughtSpecific.HSourNoTang]: 'group_em29q27/group_oh4fa74/HSourNoTang',
  [DroughtSpecific.NoSourHtang]: 'group_em29q27/group_oh4fa74/NoSourHtang',
  [DroughtSpecific.NoBtSourTan]: 'group_em29q27/group_oh4fa74/NoBtSourTan',
  [DroughtSpecific.Electric]: 'group_em29q27/group_oh4fa74/Electric',
  [DroughtSpecific.HealCenNoHo2]: 'group_em29q27/group_mv5vw26/HealCenNoHo2',
  [DroughtSpecific.HBotSourTang]: 'group_em29q27/group_mv5vw26/HBotSourTang',
  [DroughtSpecific.HaSouNoTang]: 'group_em29q27/group_mv5vw26/HaSouNoTang',
  [DroughtSpecific.NoSourHatan]: 'group_em29q27/group_mv5vw26/NoSourHatan',
  [DroughtSpecific.NoBtSouTan]: 'group_em29q27/group_mv5vw26/NoBtSouTan',
  [DroughtSpecific.ElecForHeal]: 'group_em29q27/group_mv5vw26/ElecForHeal',
  [DroughtSpecific.DamHavWater]: 'group_pa74w20/group_qu0fl63/DamHavWater',
  [DroughtSpecific.DamNoWater]: 'group_pa74w20/group_qu0fl63/DamNoWater',
  [DroughtSpecific.PondHavWat]: 'group_pa74w20/group_om0vk80/PondHavWat',
  [DroughtSpecific.PondNoWate]: 'group_pa74w20/group_om0vk80/PondNoWate',
  [DroughtSpecific.PlumWelHaWat]: 'group_pa74w20/group_uv6lk64/PlumWelHaWat',
  [DroughtSpecific.PluWelNoWat]: 'group_pa74w20/group_uv6lk64/PluWelNoWat',
  [DroughtSpecific.DigWelHaWat]: 'group_pa74w20/group_nr51r72/DigWelHaWat',
  [DroughtSpecific.DigWelNoWat]: 'group_pa74w20/group_nr51r72/DigWelNoWat',
  [DroughtSpecific.NuVilNedHep]: 'group_gn6qw58/group_sx5lq59/NuVilNedHep',
  [DroughtSpecific.TNuFamNeHo2]: 'group_gn6qw58/group_sx5lq59/TNuFamNeHo2',
  [DroughtSpecific.NumPeople]: 'group_gn6qw58/group_sx5lq59/NumPeople',
  [DroughtSpecific.NumMen]: 'group_gn6qw58/group_sx5lq59/NumMen',
  [DroughtSpecific.NumWomen]: 'group_gn6qw58/group_sx5lq59/NumWomen',
  [DroughtSpecific.NumKids]: 'group_gn6qw58/group_sx5lq59/NumKids',
  [DroughtSpecific.NumElder]: 'group_gn6qw58/group_sx5lq59/NumElder',
  [DroughtSpecific.NumDis]: 'group_gn6qw58/group_sx5lq59/NumDis',
  [DroughtSpecific.NumWatTank]: 'group_gn6qw58/group_ot4yf02/NumWatTank',
  [DroughtSpecific.NuStorageFam]: 'group_gn6qw58/group_ot4yf02/NuStorageFam',
  [DroughtSpecific.NumWateTank]: 'group_gn6qw58/group_ot4yf02/NumWateTank',
  [DroughtSpecific.NumFilter]: 'group_gn6qw58/group_ot4yf02/NumFilter',
  [DroughtSpecific.NumWatePur]: 'group_gn6qw58/group_ot4yf02/NumWatePur',
  [DroughtSpecific.NumWatStor]: 'group_lm0eq74/group_ei7de96/NumWatStor',
  [DroughtSpecific.WatSorRepar]: 'group_lm0eq74/group_ei7de96/WatSorRepar',
  [DroughtSpecific.WatStoRepar]: 'group_lm0eq74/group_ei7de96/WatStoRepar',
  [DroughtSpecific.SolarNeed]: 'group_lm0eq74/group_ei7de96/SolarNeed',
  [DroughtSpecific.FanNeed]: 'group_lm0eq74/group_ei7de96/FanNeed',
  [DroughtSpecific.WatStorNed]: 'group_lm0eq74/group_ni05u89/WatStorNed',
  [DroughtSpecific.WatSorRep]: 'group_lm0eq74/group_ni05u89/WatSorRep',
  [DroughtSpecific.WatStoRep]: 'group_lm0eq74/group_ni05u89/WatStoRep',
  [DroughtSpecific.NuSolarNeed]: 'group_lm0eq74/group_ni05u89/NuSolarNeed',
  [DroughtSpecific.NumFanNeed]: 'group_lm0eq74/group_ni05u89/NumFanNeed',
  [DroughtSpecific.LandSize]: 'group_lt1ab13/LandSize',
  [DroughtSpecific.PumMachine]: 'group_lt1ab13/PumMachine',
  [DroughtSpecific.NumGasoline]: 'group_lt1ab13/NumGasoline',
  [DroughtSpecific.NumFam]: 'group_lt1ab13/NumFam',
  [DroughtSpecific.FamNoIncom]: 'group_wi2jc00/FamNoIncom',
  [DroughtSpecific.PeoNoIncom]: 'group_wi2jc00/PeoNoIncom',
  [DroughtSpecific.FamNoFod]: 'group_wi2jc00/FamNoFod',
  [DroughtSpecific.PeoNoFod]: 'group_wi2jc00/PeoNoFod',
  [DroughtSpecific.NuKidColWat]: 'group_hp5cn05/NuKidColWat',
  [DroughtSpecific.IfYes]: 'group_hp5cn05/IfYes',
  [DroughtSpecific.NuWoCollWat]: 'group_hp5cn05/NuWoCollWat',
  [DroughtSpecific.Yes]: 'group_hp5cn05/Yes',
  [DroughtSpecific.TreatOccur]: 'group_hp5cn05/TreatOccur',
} as const;
