export const droughtSpecificKeys = {
  NumVillAff: 'group_dg01m69/NumVillAff',
  NumFamAff: 'group_dg01m69/group_kx2wb92/NumFamAff',
  NumPeoAff: 'group_dg01m69/group_kx2wb92/NumPeoAff',
  NumMe: 'group_dg01m69/group_kx2wb92/NumMe',
  NumFe: 'group_dg01m69/group_kx2wb92/NumFe',
  NumKid: 'group_dg01m69/group_kx2wb92/NumKid',
  NumOld: 'group_dg01m69/group_kx2wb92/NumOld',
  NumDisMising: 'group_dg01m69/group_kx2wb92/NumDisMising',
  TNumDeath: 'group_dg01m69/group_nk3zh15/TNumDeath',
  NumMeDeath: 'group_dg01m69/group_nk3zh15/NumMeDeath',
  NumFeDeath: 'group_dg01m69/group_nk3zh15/NumFeDeath',
  NumKidDeath: 'group_dg01m69/group_nk3zh15/NumKidDeath',
  NumOldDeath: 'group_dg01m69/group_nk3zh15/NumOldDeath',
  NumDisDeath: 'group_dg01m69/group_nk3zh15/NumDisDeath',
  FamAgriAff: 'group_yn34m57/group_rg2xt75/FamAgriAff',
  FarmAff: 'group_yn34m57/group_rg2xt75/FarmAff',
  FarmDam: 'group_yn34m57/group_rg2xt75/FarmDam',
  SamNabAff: 'group_yn34m57/group_rg2xt75/SamNabAff',
  SamNabDam: 'group_yn34m57/group_rg2xt75/SamNabDam',
  PaddyAff: 'group_yn34m57/group_rg2xt75/PaddyAff',
  PaddyDam: 'group_yn34m57/group_rg2xt75/PaddyDam',
  CowDeath: 'group_yn34m57/group_pl5gf73/CowDeath',
  BaffoDeath: 'group_yn34m57/group_pl5gf73/BaffoDeath',
  PigDeath: 'group_yn34m57/group_pl5gf73/PigDeath',
  BirdDeath: 'group_yn34m57/group_pl5gf73/BirdDeath',
  NumSchNoHo2: 'group_em29q27/group_oh4fa74/NumSchNoHo2',
  BotSourTang: 'group_em29q27/group_oh4fa74/BotSourTang',
  HSourNoTang: 'group_em29q27/group_oh4fa74/HSourNoTang',
  NoSourHtang: 'group_em29q27/group_oh4fa74/NoSourHtang',
  NoBtSourTan: 'group_em29q27/group_oh4fa74/NoBtSourTan',
  Electric: 'group_em29q27/group_oh4fa74/Electric',
  HealCenNoHo2: 'group_em29q27/group_mv5vw26/HealCenNoHo2',
  HBotSourTang: 'group_em29q27/group_mv5vw26/HBotSourTang',
  HaSouNoTang: 'group_em29q27/group_mv5vw26/HaSouNoTang',
  NoSourHatan: 'group_em29q27/group_mv5vw26/NoSourHatan',
  NoBtSouTan: 'group_em29q27/group_mv5vw26/NoBtSouTan',
  ElecForHeal: 'group_em29q27/group_mv5vw26/ElecForHeal',
  DamHavWater: 'group_pa74w20/group_qu0fl63/DamHavWater',
  DamNoWater: 'group_pa74w20/group_qu0fl63/DamNoWater',
  PondHavWat: 'group_pa74w20/group_om0vk80/PondHavWat',
  PondNoWate: 'group_pa74w20/group_om0vk80/PondNoWate',
  PlumWelHaWat: 'group_pa74w20/group_uv6lk64/PlumWelHaWat',
  PluWelNoWat: 'group_pa74w20/group_uv6lk64/PluWelNoWat',
  DigWelHaWat: 'group_pa74w20/group_nr51r72/DigWelHaWat',
  DigWelNoWat: 'group_pa74w20/group_nr51r72/DigWelNoWat',
  NuVilNedHep: 'group_gn6qw58/group_sx5lq59/NuVilNedHep',
  TNuFamNeHo2: 'group_gn6qw58/group_sx5lq59/TNuFamNeHo2',
  NumPeople: 'group_gn6qw58/group_sx5lq59/NumPeople',
  NumMen: 'group_gn6qw58/group_sx5lq59/NumMen',
  NumWomen: 'group_gn6qw58/group_sx5lq59/NumWomen',
  NumKids: 'group_gn6qw58/group_sx5lq59/NumKids',
  NumElder: 'group_gn6qw58/group_sx5lq59/NumElder',
  NumDis: 'group_gn6qw58/group_sx5lq59/NumDis',
  NumWatTank: 'group_gn6qw58/group_ot4yf02/NumWatTank',
  NuStorageFam: 'group_gn6qw58/group_ot4yf02/NuStorageFam',
  NumWateTank: 'group_gn6qw58/group_ot4yf02/NumWateTank',
  NumFilter: 'group_gn6qw58/group_ot4yf02/NumFilter',
  NumWatePur: 'group_gn6qw58/group_ot4yf02/NumWatePur',
  NumWatStor: 'group_lm0eq74/group_ei7de96/NumWatStor',
  WatSorRepar: 'group_lm0eq74/group_ei7de96/WatSorRepar',
  WatStoRepar: 'group_lm0eq74/group_ei7de96/WatStoRepar',
  SolarNeed: 'group_lm0eq74/group_ei7de96/SolarNeed',
  FanNeed: 'group_lm0eq74/group_ei7de96/FanNeed',
  WatStorNed: 'group_lm0eq74/group_ni05u89/WatStorNed',
  WatSorRep: 'group_lm0eq74/group_ni05u89/WatSorRep',
  WatStoRep: 'group_lm0eq74/group_ni05u89/WatStoRep',
  NuSolarNeed: 'group_lm0eq74/group_ni05u89/NuSolarNeed',
  NumFanNeed: 'group_lm0eq74/group_ni05u89/NumFanNeed',
  LandSize: 'group_lt1ab13/LandSize',
  PumMachine: 'group_lt1ab13/PumMachine',
  NumGasoline: 'group_lt1ab13/NumGasoline',
  NumFam: 'group_lt1ab13/NumFam',
  FamNoIncom: 'group_wi2jc00/FamNoIncom',
  PeoNoIncom: 'group_wi2jc00/PeoNoIncom',
  FamNoFod: 'group_wi2jc00/FamNoFod',
  PeoNoFod: 'group_wi2jc00/PeoNoFod',
  NuKidColWat: 'group_hp5cn05/NuKidColWat',
  IfYes: 'group_hp5cn05/IfYes',
  NuWoCollWat: 'group_hp5cn05/NuWoCollWat',
  Yes: 'group_hp5cn05/Yes',
  TreatOccur: 'group_hp5cn05/TreatOccur',
} as const;

export enum DroughtSpecific {
  NumVillAff = 'NumVillAff',
  NumFamAff = 'NumFamAff',
  NumPeoAff = 'NumPeoAff',
  NumMe = 'NumMe',
  NumFe = 'NumFe',
  NumKid = 'NumKid',
  NumOld = 'NumOld',
  NumDisMising = 'NumDisMising',
  TNumDeath = 'TNumDeath',
  NumMeDeath = 'NumMeDeath',
  NumFeDeath = 'NumFeDeath',
  NumKidDeath = 'NumKidDeath',
  NumOldDeath = 'NumOldDeath',
  NumDisDeath = 'NumDisDeath',
  FamAgriAff = 'FamAgriAff',
  FarmAff = 'FarmAff',
  FarmDam = 'FarmDam',
  SamNabAff = 'SamNabAff',
  SamNabDam = 'SamNabDam',
  PaddyAff = 'PaddyAff',
  PaddyDam = 'PaddyDam',
  CowDeath = 'CowDeath',
  BaffoDeath = 'BaffoDeath',
  PigDeath = 'PigDeath',
  BirdDeath = 'BirdDeath',
  NumSchNoHo2 = 'NumSchNoHo2',
  BotSourTang = 'BotSourTang',
  HSourNoTang = 'HSourNoTang',
  NoSourHtang = 'NoSourHtang',
  NoBtSourTan = 'NoBtSourTan',
  Electric = 'Electric',
  HealCenNoHo2 = 'HealCenNoHo2',
  HBotSourTang = 'HBotSourTang',
  HaSouNoTang = 'HaSouNoTang',
  NoSourHatan = 'NoSourHatan',
  NoBtSouTan = 'NoBtSouTan',
  ElecForHeal = 'ElecForHeal',
  DamHavWater = 'DamHavWater',
  DamNoWater = 'DamNoWater',
  PondHavWat = 'PondHavWat',
  PondNoWate = 'PondNoWate',
  PlumWelHaWat = 'PlumWelHaWat',
  PluWelNoWat = 'PluWelNoWat',
  DigWelHaWat = 'DigWelHaWat',
  DigWelNoWat = 'DigWelNoWat',
  NuVilNedHep = 'NuVilNedHep',
  TNuFamNeHo2 = 'TNuFamNeHo2',
  NumPeople = 'NumPeople',
  NumMen = 'NumMen',
  NumWomen = 'NumWomen',
  NumKids = 'NumKids',
  NumElder = 'NumElder',
  NumDis = 'NumDis',
  NumWatTank = 'NumWatTank',
  NuStorageFam = 'NuStorageFam',
  NumWateTank = 'NumWateTank',
  NumFilter = 'NumFilter',
  NumWatePur = 'NumWatePur',
  NumWatStor = 'NumWatStor',
  WatSorRepar = 'WatSorRepar',
  WatStoRepar = 'WatStoRepar',
  SolarNeed = 'SolarNeed',
  FanNeed = 'FanNeed',
  WatStorNed = 'WatStorNed',
  WatSorRep = 'WatSorRep',
  WatStoRep = 'WatStoRep',
  NuSolarNeed = 'NuSolarNeed',
  NumFanNeed = 'NumFanNeed',
  LandSize = 'LandSize',
  PumMachine = 'PumMachine',
  NumGasoline = 'NumGasoline',
  NumFam = 'NumFam',
  FamNoIncom = 'FamNoIncom',
  PeoNoIncom = 'PeoNoIncom',
  FamNoFod = 'FamNoFod',
  PeoNoFod = 'PeoNoFod',
  NuKidColWat = 'NuKidColWat',
  IfYes = 'IfYes',
  NuWoCollWat = 'NuWoCollWat',
  Yes = 'Yes',
  TreatOccur = 'TreatOccur',
}
