/* eslint-disable max-lines */

export enum FloodSpecific {
  floodN = 'floodN',
  NumVillAff = 'NumVillAff',
  NumFamAff = 'NumFamAff',
  NumPeoAff = 'NumPeoAff',
  NumFeAff = 'NumFeAff',
  NumTDeath = 'NumTDeath',
  NumMeDeath = 'NumMeDeath',
  NumFeDeath = 'NumFeDeath',
  NumKidDeath = 'NumKidDeath',
  NumOldDeath = 'NumOldDeath',
  NumDisDeath = 'NumDisDeath',
  NumTMissing = 'NumTMissing',
  NumMeMissing = 'NumMeMissing',
  NumFeMissing = 'NumFeMissing',
  NumKidMissing = 'NumKidMissing',
  NumOldMissing = 'NumOldMissing',
  NumDisMissing = 'NumDisMissing',
  NumTInjure = 'NumTInjure',
  NumMeInjure = 'NumMeInjure',
  NumFeInjure = 'NumFeInjure',
  NumKidInjure = 'NumKidInjure',
  NumOldInjure = 'NumOldInjure',
  NumDisInjure = 'NumDisInjure',
  NumFamEva = 'NumFamEva',
  NumPeoEva = 'NumPeoEva',
  NumMeEva = 'NumMeEva',
  NumFeEva = 'NumFeEva',
  NumKidEva = 'NumKidEva',
  NumOldEva = 'NumOldEva',
  NumDisEva = 'NumDisEva',
  NumFamRe = 'NumFamRe',
  NumPeoRe = 'NumPeoRe',
  NumMeRe = 'NumMeRe',
  NumFeRe = 'NumFeRe',
  NumKidRe = 'NumKidRe',
  NumOldRe = 'NumOldRe',
  NumDisRe = 'NumDisRe',
  NumSafePla = 'NumSafePla',
  NumPeoSEC = 'NumPeoSEC',
  NumHouAff = 'NumHouAff',
  NumHouDam = 'NumHouDam',
  NumSchoAff = 'NumSchoAff',
  NumSchoDam = 'NumSchoDam',
  NumAffHeal = 'NumAffHeal',
  NumDamHeal = 'NumDamHeal',
  NumPagoAff = 'NumPagoAff',
  NumPagoDam = 'NumPagoDam',
  NumBuilAff = 'NumBuilAff',
  NumBuilDam = 'NumBuilDam',
  NumShopAff = 'NumShopAff',
  NumShopDam = 'NumShopDam',
  NumWareHAff = 'NumWareHAff',
  NumWareHDam = 'NumWareHDam',
  NumCraftAff = 'NumCraftAff',
  NumCraftDam = 'NumCraftDam',
  FarmAff = 'FarmAff',
  FarmDam = 'FarmDam',
  SamNabAff = 'SamNabAff',
  SamNabDam = 'SamNabDam',
  PaddyAff = 'PaddyAff',
  PaddyDam = 'PaddyDam',
  CowEva = 'CowEva',
  CowDeath = 'CowDeath',
  CowMissing = 'CowMissing',
  PigEva = 'PigEva',
  PigDeath = 'PigDeath',
  PigMissing = 'PigMissing',
  BirdEva = 'BirdEva',
  BirdDeath = 'BirdDeath',
  BirdMissing = 'BirdMissing',
  RubberRoAff = 'RubberRoAff',
  RubberRoDam = 'RubberRoDam',
  ConcretAff = 'ConcretAff',
  ConcretDam = 'ConcretDam',
  RuralRoAff = 'RuralRoAff',
  RuralRoDam = 'RuralRoDam',
  BridgeAff = 'BridgeAff',
  BridgeDam = 'BridgeDam',
  BeleBridAff = 'BeleBridAff',
  BeleBridDam = 'BeleBridDam',
  DrainageAff = 'DrainageAff',
  DrainageDam = 'DrainageDam',
  DamAff = 'DamAff',
  DamDamaged = 'DamDamaged',
  WatGateAff = 'WatGateAff',
  WatGateDam = 'WatGateDam',
  PlumWelAff = 'PlumWelAff',
  PlumWelDam = 'PlumWelDam',
  DigWellAff = 'DigWellAff',
  DigWellDam = 'DigWellDam',
  PondAff = 'PondAff',
  PondDam = 'PondDam',
  LatrineAff = 'LatrineAff',
  LatrineDam = 'LatrineDam',
  RiverBreak = 'RiverBreak',
  RiverBreakLo = 'RiverBreakLo',
  BrolayAff = 'BrolayAff', // not used
  BrolayDam = 'BrolayDam', // not used
  NumFamTent = 'NumFamTent',
  NumPeoTent = 'NumPeoTent',
  NumFamBuil = 'NumFamBuil',
  NumPeoBuil = 'NumPeoBuil',
  NumFamRela = 'NumFamRela',
  NumPeoRela = 'NumPeoRela',
  NumTemSch = 'NumTemSch',
  StuAcTemSch = 'StuAcTemSch',
  SchUseSafe = 'SchUseSafe',
  NumStu = 'NumStu',
  NumSchStop = 'NumSchStop',
  NumStuNoCla = 'NumStuNoCla',
  NumFamNoWa = 'NumFamNoWa',
  NumPeoNoWa = 'NumPeoNoWa',
  TimeAceWa = 'TimeAceWa',
  NuFamNoWaEq = 'NuFamNoWaEq',
  NuFamNoLat = 'NuFamNoLat',
  NonActingH = 'NonActingH',
  PeoCanAceH = 'PeoCanAceH',
  NumDoctor = 'NumDoctor',
  NumNurse = 'NumNurse',
  NumStaff = 'NumStaff',
  NumFamNoFod = 'NumFamNoFod',
  NumPeoNoFod = 'NumPeoNoFod',
  FamNoFod7d = 'FamNoFod7d',
  NumActShop = 'NumActShop',
  NumNoActShop = 'NumNoActShop',
  RicePrice = 'RicePrice',
  threat = 'threat',
  other = 'other',
}

export const floodSpecificKeys = {
  [FloodSpecific.floodN]: 'g2/flood_n',
  [FloodSpecific.NumVillAff]: 'g3/g3_1/NumVillAff',
  [FloodSpecific.NumFamAff]: 'g3/g3_1/g3_2/NumFamAff',
  [FloodSpecific.NumPeoAff]: 'g3/g3_1/g3_2/NumPeoAff',
  [FloodSpecific.NumFeAff]: 'g3/g3_1/g3_2/NumFeAff',
  [FloodSpecific.NumTDeath]: 'g3/g4/TNumDeath',
  [FloodSpecific.NumMeDeath]: 'g3/g4/NumMeDeath',
  [FloodSpecific.NumFeDeath]: 'g3/g4/NumFeDeath',
  [FloodSpecific.NumKidDeath]: 'g3/g4/NumKidDeath',
  [FloodSpecific.NumOldDeath]: 'g3/g4/NumOldDeath',
  [FloodSpecific.NumDisDeath]: 'g3/g4/NumDisDeath',
  [FloodSpecific.NumTMissing]: 'g3/g5/NumTMising',
  [FloodSpecific.NumMeMissing]: 'g3/g5/NumMeMising',
  [FloodSpecific.NumFeMissing]: 'g3/g5/NumFeMising',
  [FloodSpecific.NumKidMissing]: 'g3/g5/NumKidMising',
  [FloodSpecific.NumOldMissing]: 'g3/g5/NumOldMising',
  [FloodSpecific.NumDisMissing]: 'g3/g5/NumDisMising',
  [FloodSpecific.NumTInjure]: 'g3/g6/NumTInjure',
  [FloodSpecific.NumMeInjure]: 'g3/g6/NumMeInjure',
  [FloodSpecific.NumFeInjure]: 'g3/g6/NumFeInjure',
  [FloodSpecific.NumKidInjure]: 'g3/g6/NumKidInjure',
  [FloodSpecific.NumOldInjure]: 'g3/g6/NumOldInjure',
  [FloodSpecific.NumDisInjure]: 'g3/g6/NumDisInjure',
  [FloodSpecific.NumFamEva]: 'g3/g7/NumFamEva',
  [FloodSpecific.NumPeoEva]: 'g3/g7/NumPeoEva',
  [FloodSpecific.NumMeEva]: 'g3/g7/NumMeEva',
  [FloodSpecific.NumFeEva]: 'g3/g7/NumFeEva',
  [FloodSpecific.NumKidEva]: 'g3/g7/NumKidEva',
  [FloodSpecific.NumOldEva]: 'g3/g7/NumOldEva',
  [FloodSpecific.NumDisEva]: 'g3/g7/NumDisEva',
  [FloodSpecific.NumFamRe]: 'g3/g8/NumFamRe',
  [FloodSpecific.NumPeoRe]: 'g3/g8/NumPeoRe',
  [FloodSpecific.NumMeRe]: 'g3/g8/NumMeRe',
  [FloodSpecific.NumFeRe]: 'g3/g8/NumFeRe',
  [FloodSpecific.NumKidRe]: 'g3/g8/NumKidRe',
  [FloodSpecific.NumOldRe]: 'g3/g8/NumOldRe',
  [FloodSpecific.NumDisRe]: 'g3/g8/NumDisRe',
  [FloodSpecific.NumSafePla]: 'g3/g9/NumSafePla',
  [FloodSpecific.NumPeoSEC]: 'g3/g9/NumPeoSEC',
  [FloodSpecific.NumHouAff]: 'g10/g10_1/NumHouAff',
  [FloodSpecific.NumHouDam]: 'g10/g10_1/NumHouDam',
  [FloodSpecific.NumSchoAff]: 'g10/g10_2/NumSchoAff',
  [FloodSpecific.NumSchoDam]: 'g10/g10_2/NumSchoDam',
  [FloodSpecific.NumAffHeal]: 'g10/g10_3/NumAffHeal',
  [FloodSpecific.NumDamHeal]: 'g10/g10_3/NumDamHeal',
  [FloodSpecific.NumPagoAff]: 'g10/g10_4/NumPagoAff',
  [FloodSpecific.NumPagoDam]: 'g10/g10_4/NumPagoDam',
  [FloodSpecific.NumBuilAff]: 'g10/g10_5/NumBuilAff',
  [FloodSpecific.NumBuilDam]: 'g10/g10_5/NumBuilDam',
  [FloodSpecific.NumShopAff]: 'g10/g10_6/NumShopAff',
  [FloodSpecific.NumShopDam]: 'g10/g10_6/NumShopDam',
  [FloodSpecific.NumWareHAff]: 'g10/g10_7/NumWareHAff',
  [FloodSpecific.NumWareHDam]: 'g10/g10_7/NumWareHDam',
  [FloodSpecific.NumCraftAff]: 'g10/g10_8/NumCraftAff',
  [FloodSpecific.NumCraftDam]: 'g10/g10_8/NumCraftDam',
  [FloodSpecific.FarmAff]: 'g11/g11_1/FarmAff',
  [FloodSpecific.FarmDam]: 'g11/g11_1/FarmDam',
  [FloodSpecific.SamNabAff]: 'g11/g11_2/SamNabAff',
  [FloodSpecific.SamNabDam]: 'g11/g11_2/SamNabDam',
  [FloodSpecific.PaddyAff]: 'g11/g11_3/PaddyAff',
  [FloodSpecific.PaddyDam]: 'g11/g11_3/PaddyDam',
  [FloodSpecific.CowEva]: 'g11/g11_4/CowEva',
  [FloodSpecific.CowDeath]: 'g11/g11_4/CowDeath',
  [FloodSpecific.CowMissing]: 'g11/g11_4/CowMissing',
  [FloodSpecific.PigEva]: 'g11/g11_5/PigEva',
  [FloodSpecific.PigDeath]: 'g11/g11_5/PigDeath',
  [FloodSpecific.PigMissing]: 'g11/g11_5/PigMissing',
  [FloodSpecific.BirdEva]: 'g11/g11_6/BirdEva',
  [FloodSpecific.BirdDeath]: 'g11/g11_6/BirdDeath',
  [FloodSpecific.BirdMissing]: 'g11/g11_6/BirdMissing',
  [FloodSpecific.RubberRoAff]: 'g12/g12_1/RubberRoAff',
  [FloodSpecific.RubberRoDam]: 'g12/g12_1/RubberRoDam',
  [FloodSpecific.ConcretAff]: 'g12/g12_2/ConcretAff',
  [FloodSpecific.ConcretDam]: 'g12/g12_2/ConcretDam',
  [FloodSpecific.RuralRoAff]: 'g12/g12_3/RuralRoAff',
  [FloodSpecific.RuralRoDam]: 'g12/g12_3/RuralRoDam',
  [FloodSpecific.BridgeAff]: 'g12/g12_4/BridgeAff',
  [FloodSpecific.BridgeDam]: 'g12/g12_4/BridgeDam',
  [FloodSpecific.BeleBridAff]: 'g12/g12_5/BeleBridAff',
  [FloodSpecific.BeleBridDam]: 'g12/g12_5/BeleBridDam',
  [FloodSpecific.DrainageAff]: 'g12/g12_6/DrainageAff',
  [FloodSpecific.DrainageDam]: 'g12/g12_6/DrainageDam',
  [FloodSpecific.DamAff]: 'g13/g13_1/DamAff',
  [FloodSpecific.DamDamaged]: 'g13/g13_1/DamDamaged',
  [FloodSpecific.WatGateAff]: 'g13/g13_2/WatGateAff',
  [FloodSpecific.WatGateDam]: 'g13/g13_2/WatGateDam',
  [FloodSpecific.PlumWelAff]: 'g13/g13_3/PlumWelAff',
  [FloodSpecific.PlumWelDam]: 'g13/g13_3/PlumWelDam',
  [FloodSpecific.DigWellAff]: 'g13/g13_4/DigWellAff',
  [FloodSpecific.DigWellDam]: 'g13/g13_4/DigWellDam',
  [FloodSpecific.PondAff]: 'g13/g13_5/PondAff',
  [FloodSpecific.PondDam]: 'g13/g13_5/PondDam',
  [FloodSpecific.LatrineAff]: 'g13/g13_6/LatrineAff',
  [FloodSpecific.LatrineDam]: 'g13/g13_6/LatrineDam',
  [FloodSpecific.RiverBreak]: 'g13/g13_7/RiverBreak',
  [FloodSpecific.RiverBreakLo]: 'g13/g13_7/RiverBreakLo',
  [FloodSpecific.BrolayAff]: 'g13/BrolayAff',
  [FloodSpecific.BrolayDam]: 'g13/BrolayDam',
  [FloodSpecific.NumFamTent]: 'g14/g14_1/NumFamTent',
  [FloodSpecific.NumPeoTent]: 'g14/g14_1/NumPeoTent',
  [FloodSpecific.NumFamBuil]: 'g14/g14_2/NumFamBuil',
  [FloodSpecific.NumPeoBuil]: 'g14/g14_2/NumPeoBuil',
  [FloodSpecific.NumFamRela]: 'g14/g14_3/NumFamRela',
  [FloodSpecific.NumPeoRela]: 'g14/g14_3/NumPeoRela',
  [FloodSpecific.NumTemSch]: 'g15/g15_1/NumTemSch',
  [FloodSpecific.StuAcTemSch]: 'g15/g15_1/StuAcTemSch',
  [FloodSpecific.SchUseSafe]: 'g15/g15_2/SchUseSafe',
  [FloodSpecific.NumStu]: 'g15/g15_2/NumStu',
  [FloodSpecific.NumSchStop]: 'g15/g15_3/NumSchStop',
  [FloodSpecific.NumStuNoCla]: 'g15/g15_3/NumStuNoCla',
  [FloodSpecific.NumFamNoWa]: 'g16_1/g16_1_001/NumFamNoWa',
  [FloodSpecific.NumPeoNoWa]: 'g16_1/g16_1_001/NumPeoNoWa',
  [FloodSpecific.TimeAceWa]: 'g16_1/g16_1_001/TimeAceWa',
  [FloodSpecific.NuFamNoWaEq]: 'g16_1/g16_1_001/NuFamNoWaEq',
  [FloodSpecific.NuFamNoLat]: 'g16_1/g16_1_001/NuFamNoLat',
  [FloodSpecific.NonActingH]: 'g17/g17_1/NonActingH',
  [FloodSpecific.PeoCanAceH]: 'g17/g17_1/PeoCanAceH',
  [FloodSpecific.NumDoctor]: 'g17/g17_1/NumDoctor',
  [FloodSpecific.NumNurse]: 'g17/g17_1/NumNurse',
  [FloodSpecific.NumStaff]: 'g17/g17_1/NumStaff',
  [FloodSpecific.NumFamNoFod]: 'g18/g18_1/NumFamNoFod',
  [FloodSpecific.NumPeoNoFod]: 'g18/g18_1/NumPeoNoFod',
  [FloodSpecific.FamNoFod7d]: 'g18/FamNoFod7d',
  [FloodSpecific.NumActShop]: 'g18/g18_2/NumActShop',
  [FloodSpecific.NumNoActShop]: 'g18/g18_2/NumNoActShop',
  [FloodSpecific.RicePrice]: 'g18/RicePrice',
  [FloodSpecific.threat]: 'g19/threat',
  [FloodSpecific.other]: 'g19/other',
} as const;

export type FloodSpecificType = Record<keyof typeof floodSpecificKeys, string | undefined>;
