/* eslint-disable max-lines */

export const floodSpecificKeys = {
  NumVillAff: 'g3/g3_1/NumVillAff',
  NumFamAff: 'g3/g3_1/g3_2/NumFamAff',
  NumPeoAff: 'g3/g3_1/g3_2/NumPeoAff',
  NumFeAff: 'g3/g3_1/g3_2/NumFeAff',
  NumTDeath: 'g3/g4/TNumDeath',
  NumMeDeath: 'g3/g4/NumMeDeath',
  NumFeDeath: 'g3/g4/NumFeDeath',
  NumKidDeath: 'g3/g4/NumKidDeath',
  NumOldDeath: 'g3/g4/NumOldDeath',
  NumDisDeath: 'g3/g4/NumDisDeath',
  NumTMissing: 'g3/g5/NumTMising',
  NumMeMissing: 'g3/g5/NumMeMising',
  NumFeMissing: 'g3/g5/NumFeMising',
  NumKidMissing: 'g3/g5/NumKidMising',
  NumOldMissing: 'g3/g5/NumOldMising',
  NumDisMissing: 'g3/g5/NumDisMising',
  NumTInjure: 'g3/g6/NumTInjure',
  NumMeInjure: 'g3/g6/NumMeInjure',
  NumFeInjure: 'g3/g6/NumFeInjure',
  NumKidInjure: 'g3/g6/NumKidInjure',
  NumOldInjure: 'g3/g6/NumOldInjure',
  NumDisInjure: 'g3/g6/NumDisInjure',
  NumFamEva: 'g3/g7/NumFamEva',
  NumPeoEva: 'g3/g7/NumPeoEva',
  NumMeEva: 'g3/g7/NumMeEva',
  NumFeEva: 'g3/g7/NumFeEva',
  NumKidEva: 'g3/g7/NumKidEva',
  NumOldEva: 'g3/g7/NumOldEva',
  NumDisEva: 'g3/g7/NumDisEva',
  NumFamRe: 'g3/g8/NumFamRe',
  NumPeoRe: 'g3/g8/NumPeoRe',
  NumMeRe: 'g3/g8/NumMeRe',
  NumFeRe: 'g3/g8/NumFeRe',
  NumKidRe: 'g3/g8/NumKidRe',
  NumOldRe: 'g3/g8/NumOldRe',
  NumDisRe: 'g3/g8/NumDisRe',
  NumSafePla: 'g3/g9/NumSafePla',
  NumPeoSEC: 'g3/g9/NumPeoSEC',
  NumHouAff: 'g10/g10_1/NumHouAff',
  NumHouDam: 'g10/g10_1/NumHouDam',
  NumSchoAff: 'g10/g10_2/NumSchoAff',
  NumSchoDam: 'g10/g10_2/NumSchoDam',
  NumAffHeal: 'g10/g10_3/NumAffHeal',
  NumDamHeal: 'g10/g10_3/NumDamHeal',
  NumPagoAff: 'g10/g10_4/NumPagoAff',
  NumPagoDam: 'g10/g10_4/NumPagoDam',
  NumBuilAff: 'g10/g10_5/NumBuilAff',
  NumBuilDam: 'g10/g10_5/NumBuilDam',
  NumShopAff: 'g10/g10_6/NumShopAff',
  NumShopDam: 'g10/g10_6/NumShopDam',
  NumWareHAff: 'g10/g10_7/NumWareHAff',
  NumWareHDam: 'g10/g10_7/NumWareHDam',
  NumCraftAff: 'g10/g10_8/NumCraftAff',
  NumCraftDam: 'g10/g10_8/NumCraftDam',
  FarmAff: 'g11/g11_1/FarmAff',
  FarmDam: 'g11/g11_1/FarmDam',
  SamNabAff: 'g11/g11_2/SamNabAff',
  SamNabDam: 'g11/g11_2/SamNabDam',
  PaddyAff: 'g11/g11_3/PaddyAff',
  PaddyDam: 'g11/g11_3/PaddyDam',
  CowEva: 'g11/g11_4/CowEva',
  CowDeath: 'g11/g11_4/CowDeath',
  CowMissing: 'g11/g11_4/CowMissing',
  PigEva: 'g11/g11_5/PigEva',
  PigDeath: 'g11/g11_5/PigDeath',
  PigMissing: 'g11/g11_5/PigMissing',
  BirdEva: 'g11/g11_6/BirdEva',
  BirdDeath: 'g11/g11_6/BirdDeath',
  BirdMissing: 'g11/g11_6/BirdMissing',
  RubberRoAff: 'g12/g12_1/RubberRoAff',
  RubberRoDam: 'g12/g12_1/RubberRoDam',
  ConcretAff: 'g12/g12_2/ConcretAff',
  ConcretDam: 'g12/g12_2/ConcretDam',
  RuralRoAff: 'g12/g12_3/RuralRoAff',
  RuralRoDam: 'g12/g12_3/RuralRoDam',
  BridgeAff: 'g12/g12_4/BridgeAff',
  BridgeDam: 'g12/g12_4/BridgeDam',
  BeleBridAff: 'g12/g12_5/BeleBridAff',
  BeleBridDam: 'g12/g12_5/BeleBridDam',
  DrainageAff: 'g12/g12_6/DrainageAff',
  DrainageDam: 'g12/g12_6/DrainageDam',
  DamAff: 'g13/g13_1/DamAff',
  DamDamaged: 'g13/g13_1/DamDamaged',
  WatGateAff: 'g13/g13_2/WatGateAff',
  WatGateDam: 'g13/g13_2/WatGateDam',
  PlumWelAff: 'g13/g13_3/PlumWelAff',
  PlumWelDam: 'g13/g13_3/PlumWelDam',
  DigWellAff: 'g13/g13_4/DigWellAff',
  DigWellDam: 'g13/g13_4/DigWellDam',
  PondAff: 'g13/g13_5/PondAff',
  PondDam: 'g13/g13_5/PondDam',
  LatrineAff: 'g13/g13_6/LatrineAff',
  LatrineDam: 'g13/g13_6/LatrineDam',
  RiverBreak: 'g13/g13_7/RiverBreak',
  RiverBreakLo: 'g13/g13_7/RiverBreakLo',
  BrolayAff: 'g13/BrolayAff',
  BrolayDam: 'g13/BrolayDam',
  NumFamTent: 'g14/g14_1/NumFamTent',
  NumPeoTent: 'g14/g14_1/NumPeoTent',
  NumFamBuil: 'g14/g14_2/NumFamBuil',
  NumPeoBuil: 'g14/g14_2/NumPeoBuil',
  NumFamRela: 'g14/g14_3/NumFamRela',
  NumPeoRela: 'g14/g14_3/NumPeoRela',
  NumTemSch: 'g15/g15_1/NumTemSch',
  StuAcTemSch: 'g15/g15_1/StuAcTemSch',
  SchUseSafe: 'g15/g15_2/SchUseSafe',
  NumStu: 'g15/g15_2/NumStu',
  NumSchStop: 'g15/g15_3/NumSchStop',
  NumStuNoCla: 'g15/g15_3/NumStuNoCla',
  NumFamNoWa: 'g16_1/g16_1_001/NumFamNoWa',
  NumPeoNoWa: 'g16_1/g16_1_001/NumPeoNoWa',
  TimeAceWa: 'g16_1/g16_1_001/TimeAceWa',
  NuFamNoWaEq: 'g16_1/g16_1_001/NuFamNoWaEq',
  NuFamNoLat: 'g16_1/g16_1_001/NuFamNoLat',
  NonActingH: 'g17/g17_1/NonActingH',
  PeoCanAceH: 'g17/g17_1/PeoCanAceH',
  NumDoctor: 'g17/g17_1/NumDoctor',
  NumNurse: 'g17/g17_1/NumNurse',
  NumStaff: 'g17/g17_1/NumStaff',
  NumFamNoFod: 'g18/g18_1/NumFamNoFod',
  NumPeoNoFod: 'g18/g18_1/NumPeoNoFod',
  FamNoFod7d: 'g18/FamNoFod7d',
  NumActShop: 'g18/g18_2/NumActShop',
  NumNoActShop: 'g18/g18_2/NumNoActShop',
  RicePrice: 'g18/RicePrice',
  threat: 'g19/threat',
  other: 'g19/other',
} as const;

export enum FloodSpecific {
  NumVillAff = 'NumVillAff',
  NumFamAff = 'NumFamAff',
  NumPeoAff = 'NumPeoAff',
  NumFeAff = 'NumFeAff',
  NumTDeath = 'NumTDeath',
  NumMeDeath = 'NumMeDeath',
  NumFeDeath = 'NumFeDeath',
  NumKidDeath = 'NumKidDeath',
  NumOldDeath = 'NumOldDeath',
  NumDisDeath = 'NumDisDeath',
  NumTMissing = 'NumTMissing',
  NumMeMissing = 'NumMeMissing',
  NumFeMissing = 'NumFeMissing',
  NumKidMissing = 'NumKidMissing',
  NumOldMissing = 'NumOldMissing',
  NumDisMissing = 'NumDisMissing',
  NumTInjure = 'NumTInjure',
  NumMeInjure = 'NumMeInjure',
  NumFeInjure = 'NumFeInjure',
  NumKidInjure = 'NumKidInjure',
  NumOldInjure = 'NumOldInjure',
  NumDisInjure = 'NumDisInjure',
  NumFamEva = 'NumFamEva',
  NumPeoEva = 'NumPeoEva',
  NumMeEva = 'NumMeEva',
  NumFeEva = 'NumFeEva',
  NumKidEva = 'NumKidEva',
  NumOldEva = 'NumOldEva',
  NumDisEva = 'NumDisEva',
  NumFamRe = 'NumFamRe',
  NumPeoRe = 'NumPeoRe',
  NumMeRe = 'NumMeRe',
  NumFeRe = 'NumFeRe',
  NumKidRe = 'NumKidRe',
  NumOldRe = 'NumOldRe',
  NumDisRe = 'NumDisRe',
  NumSafePla = 'NumSafePla',
  NumPeoSEC = 'NumPeoSEC',
  NumHouAff = 'NumHouAff',
  NumHouDam = 'NumHouDam',
  NumSchoAff = 'NumSchoAff',
  NumSchoDam = 'NumSchoDam',
  NumAffHeal = 'NumAffHeal',
  NumDamHeal = 'NumDamHeal',
  NumPagoAff = 'NumPagoAff',
  NumPagoDam = 'NumPagoDam',
  NumBuilAff = 'NumBuilAff',
  NumBuilDam = 'NumBuilDam',
  NumShopAff = 'NumShopAff',
  NumShopDam = 'NumShopDam',
  NumWareHAff = 'NumWareHAff',
  NumWareHDam = 'NumWareHDam',
  NumCraftAff = 'NumCraftAff',
  NumCraftDam = 'NumCraftDam',
  FarmAff = 'FarmAff',
  FarmDam = 'FarmDam',
  SamNabAff = 'SamNabAff',
  SamNabDam = 'SamNabDam',
  PaddyAff = 'PaddyAff',
  PaddyDam = 'PaddyDam',
  CowEva = 'CowEva',
  CowDeath = 'CowDeath',
  CowMissing = 'CowMissing',
  PigEva = 'PigEva',
  PigDeath = 'PigDeath',
  PigMissing = 'PigMissing',
  BirdEva = 'BirdEva',
  BirdDeath = 'BirdDeath',
  BirdMissing = 'BirdMissing',
  RubberRoAff = 'RubberRoAff',
  RubberRoDam = 'RubberRoDam',
  ConcretAff = 'ConcretAff',
  ConcretDam = 'ConcretDam',
  RuralRoAff = 'RuralRoAff',
  RuralRoDam = 'RuralRoDam',
  BridgeAff = 'BridgeAff',
  BridgeDam = 'BridgeDam',
  BeleBridAff = 'BeleBridAff',
  BeleBridDam = 'BeleBridDam',
  DrainageAff = 'DrainageAff',
  DrainageDam = 'DrainageDam',
  DamAff = 'DamAff',
  DamDamaged = 'DamDamaged',
  WatGateAff = 'WatGateAff',
  WatGateDam = 'WatGateDam',
  PlumWelAff = 'PlumWelAff',
  PlumWelDam = 'PlumWelDam',
  DigWellAff = 'DigWellAff',
  DigWellDam = 'DigWellDam',
  PondAff = 'PondAff',
  PondDam = 'PondDam',
  LatrineAff = 'LatrineAff',
  LatrineDam = 'LatrineDam',
  RiverBreak = 'RiverBreak',
  RiverBreakLo = 'RiverBreakLo',
  BrolayAff = 'BrolayAff',
  BrolayDam = 'BrolayDam',
  NumFamTent = 'NumFamTent',
  NumPeoTent = 'NumPeoTent',
  NumFamBuil = 'NumFamBuil',
  NumPeoBuil = 'NumPeoBuil',
  NumFamRela = 'NumFamRela',
  NumPeoRela = 'NumPeoRela',
  NumTemSch = 'NumTemSch',
  StuAcTemSch = 'StuAcTemSch',
  SchUseSafe = 'SchUseSafe',
  NumStu = 'NumStu',
  NumSchStop = 'NumSchStop',
  NumStuNoCla = 'NumStuNoCla',
  NumFamNoWa = 'NumFamNoWa',
  NumPeoNoWa = 'NumPeoNoWa',
  TimeAceWa = 'TimeAceWa',
  NuFamNoWaEq = 'NuFamNoWaEq',
  NuFamNoLat = 'NuFamNoLat',
  NonActingH = 'NonActingH',
  PeoCanAceH = 'PeoCanAceH',
  NumDoctor = 'NumDoctor',
  NumNurse = 'NumNurse',
  NumStaff = 'NumStaff',
  NumFamNoFod = 'NumFamNoFod',
  NumPeoNoFod = 'NumPeoNoFod',
  FamNoFod7d = 'FamNoFod7d',
  NumActShop = 'NumActShop',
  NumNoActShop = 'NumNoActShop',
  RicePrice = 'RicePrice',
  threat = 'threat',
  other = 'other',
}
