/* eslint-disable max-lines */

export const incidentSpecificKeys = {
  NumVillAff: 'group_tc1fy38/group_pf1pd97/NumVillAff',
  NumFamAff: 'group_tc1fy38/group_pf1pd97/NumFamAff',
  NumPeoAff: 'group_tc1fy38/group_pf1pd97/NumPeoAff',
  NumFeAff: 'group_tc1fy38/group_pf1pd97/NumFeAff',
  NumDeathTo: 'group_tc1fy38/group_bz3jq33/NumDeathTo',
  NumMeDeath: 'group_tc1fy38/group_bz3jq33/NumMeDeath',
  NumFeDeath: 'group_tc1fy38/group_bz3jq33/NumFeDeath',
  NumKidDeath: 'group_tc1fy38/group_bz3jq33/NumKidDeath',
  NumOldDeath: 'group_tc1fy38/group_bz3jq33/NumOldDeath',
  NumDisDeath: 'group_tc1fy38/group_bz3jq33/NumDisDeath',
  ToNumMising: 'group_tc1fy38/group_th37h10/ToNumMising',
  NumMeMising: 'group_tc1fy38/group_th37h10/NumMeMising',
  NumFeMising: 'group_tc1fy38/group_th37h10/NumFeMising',
  NumKidMising: 'group_tc1fy38/group_th37h10/NumKidMising',
  NumOldMising: 'group_tc1fy38/group_th37h10/NumOldMising',
  NumDisMising: 'group_tc1fy38/group_th37h10/NumDisMising',
  ToNumInjure: 'group_tc1fy38/group_sa7hz27/ToNumInjure',
  NumMeInjure: 'group_tc1fy38/group_sa7hz27/NumMeInjure',
  NumFeInjure: 'group_tc1fy38/group_sa7hz27/NumFeInjure',
  NumKidInjure: 'group_tc1fy38/group_sa7hz27/NumKidInjure',
  NumOldInjure: 'group_tc1fy38/group_sa7hz27/NumOldInjure',
  NumDisInjure: 'group_tc1fy38/group_sa7hz27/NumDisInjure',
  NumFamEva: 'group_tc1fy38/group_sg8yl06/NumFamEva',
  NumPeoEva: 'group_tc1fy38/group_sg8yl06/NumPeoEva',
  NumMeEva: 'group_tc1fy38/group_sg8yl06/NumMeEva',
  NumFeEva: 'group_tc1fy38/group_sg8yl06/NumFeEva',
  NumKidEva: 'group_tc1fy38/group_sg8yl06/NumKidEva',
  NumOldEva: 'group_tc1fy38/group_sg8yl06/NumOldEva',
  NumDisEva: 'group_tc1fy38/group_sg8yl06/NumDisEva',
  NumFamRe: 'group_tc1fy38/group_mq8uz76/NumFamRe',
  NumPeoRe: 'group_tc1fy38/group_mq8uz76/NumPeoRe',
  NumMeRe: 'group_tc1fy38/group_mq8uz76/NumMeRe',
  NumFeRe: 'group_tc1fy38/group_mq8uz76/NumFeRe',
  NumKidRe: 'group_tc1fy38/group_mq8uz76/NumKidRe',
  NumOldRe: 'group_tc1fy38/group_mq8uz76/NumOldRe',
  NumDisRe: 'group_tc1fy38/group_mq8uz76/NumDisRe',
  PartlyBurn: 'group_fh3jp70/group_cn0sw74/PartlyBurn',
  CompletBurn: 'group_fh3jp70/group_cn0sw74/CompletBurn',
  SchAff: 'group_fh3jp70/group_ez5mr58/SchAff',
  SchDam: 'group_fh3jp70/group_ez5mr58/SchDam',
  HealthAff: 'group_fh3jp70/group_bj6tu99/HealthAff',
  HealthDam: 'group_fh3jp70/group_bj6tu99/HealthDam',
  RivBreakLo: 'group_fh3jp70/group_pv8hz72/RivBreakLo',
  RivBreakWid: 'group_fh3jp70/group_pv8hz72/RivBreakWid',
  NationalRod: 'group_fh3jp70/group_pv8hz72/NationalRod',
  RuralRoad: 'group_fh3jp70/group_pv8hz72/RuralRoad',
  Bridge: 'group_fh3jp70/group_pv8hz72/Bridge',
  PagoAff: 'group_pk03i04/group_wa9cj38/PagoAff',
  PagoDam: 'group_pk03i04/group_wa9cj38/PagoDam',
  BuildingAff: 'group_pk03i04/group_fg5ko43/BuildingAff',
  BuildingDam: 'group_pk03i04/group_fg5ko43/BuildingDam',
  MarketAff: 'group_pk03i04/group_hi74i16/MarketAff',
  MarketDam: 'group_pk03i04/group_hi74i16/MarketDam',
  StorageAff: 'group_pk03i04/group_lf9ou90/StorageAff',
  StorageDam: 'group_pk03i04/group_lf9ou90/StorageDam',
  CraftAff: 'group_pk03i04/group_ub2hp14/CraftAff',
  CraftDam: 'group_pk03i04/group_ub2hp14/CraftDam',
  CropAff: 'group_gh6ag70/group_na4yi04/CropAff',
  CropDam: 'group_gh6ag70/group_na4yi04/CropDam',
  SamnabAff: 'group_gh6ag70/group_yh83p68/SamnabAff',
  SamnabDam: 'group_gh6ag70/group_yh83p68/SamnabDam',
  PaddyAff: 'group_gh6ag70/group_en38q31/PaddyAff',
  PaddyDam: 'group_gh6ag70/group_en38q31/PaddyDam',
  CowDeath: 'group_gh6ag70/group_wb0mf29/CowDeath',
  BaffoDeath: 'group_gh6ag70/group_wb0mf29/BaffoDeath',
  PigDeath: 'group_gh6ag70/group_wb0mf29/PigDeath',
  ChickDeath: 'group_gh6ag70/group_wb0mf29/ChickDeath',
  NumJungleAf: 'group_gh6ag70/group_gu1xp89/NumJungleAf',
  FarmAf: 'group_gh6ag70/group_gu1xp89/FarmAf',
} as const;

export enum IncidentSpecific {
  NumVillAff = 'NumVillAff',
  NumFamAff = 'NumFamAff',
  NumPeoAff = 'NumPeoAff',
  NumFeAff = 'NumFeAff',
  NumDeathTo = 'NumDeathTo',
  NumMeDeath = 'NumMeDeath',
  NumFeDeath = 'NumFeDeath',
  NumKidDeath = 'NumKidDeath',
  NumOldDeath = 'NumOldDeath',
  NumDisDeath = 'NumDisDeath',
  ToNumMising = 'ToNumMising',
  NumMeMising = 'NumMeMising',
  NumFeMising = 'NumFeMising',
  NumKidMising = 'NumKidMising',
  NumOldMising = 'NumOldMising',
  NumDisMising = 'NumDisMising',
  ToNumInjure = 'ToNumInjure',
  NumMeInjure = 'NumMeInjure',
  NumFeInjure = 'NumFeInjure',
  NumKidInjure = 'NumKidInjure',
  NumOldInjure = 'NumOldInjure',
  NumDisInjure = 'NumDisInjure',
  NumFamEva = 'NumFamEva',
  NumPeoEva = 'NumPeoEva',
  NumMeEva = 'NumMeEva',
  NumFeEva = 'NumFeEva',
  NumKidEva = 'NumKidEva',
  NumOldEva = 'NumOldEva',
  NumDisEva = 'NumDisEva',
  NumFamRe = 'NumFamRe',
  NumPeoRe = 'NumPeoRe',
  NumMeRe = 'NumMeRe',
  NumFeRe = 'NumFeRe',
  NumKidRe = 'NumKidRe',
  NumOldRe = 'NumOldRe',
  NumDisRe = 'NumDisRe',
  PartlyBurn = 'PartlyBurn',
  CompletBurn = 'CompletBurn',
  SchAff = 'SchAff',
  SchDam = 'SchDam',
  HealthAff = 'HealthAff',
  HealthDam = 'HealthDam',
  RivBreakLo = 'RivBreakLo',
  RivBreakWid = 'RivBreakWid',
  NationalRod = 'NationalRod',
  RuralRoad = 'RuralRoad',
  Bridge = 'Bridge',
  PagoAff = 'PagoAff',
  PagoDam = 'PagoDam',
  BuildingAff = 'BuildingAff',
  BuildingDam = 'BuildingDam',
  MarketAff = 'MarketAff',
  MarketDam = 'MarketDam',
  StorageAff = 'StorageAff',
  StorageDam = 'StorageDam',
  CraftAff = 'CraftAff',
  CraftDam = 'CraftDam',
  CropAff = 'CropAff',
  CropDam = 'CropDam',
  SamnabAff = 'SamnabAff',
  SamnabDam = 'SamnabDam',
  PaddyAff = 'PaddyAff',
  PaddyDam = 'PaddyDam',
  CowDeath = 'CowDeath',
  BaffoDeath = 'BaffoDeath',
  PigDeath = 'PigDeath',
  ChickDeath = 'ChickDeath',
  NumJungleAf = 'NumJungleAf',
  FarmAf = 'FarmAf',
}
