/* eslint-disable max-lines */

export enum IncidentSpecific {
  NumVillAff = 'NumVillAff',
  NumFamAff = 'NumFamAff',
  NumPeoAff = 'NumPeoAff',
  NumFeAff = 'NumFeAff',
  NumDeathTo = 'NumDeathTo',
  NumMeDeath = 'NumMeDeath',
  NumFeDeath = 'NumFeDeath',
  NumKidDeath = 'NumKidDeath',
  NumOldDeath = 'NumOldDeath',
  NumDisDeath = 'NumDisDeath',
  ToNumMising = 'ToNumMising',
  NumMeMising = 'NumMeMising',
  NumFeMising = 'NumFeMising',
  NumKidMising = 'NumKidMising',
  NumOldMising = 'NumOldMising',
  NumDisMising = 'NumDisMising',
  ToNumInjure = 'ToNumInjure',
  NumMeInjure = 'NumMeInjure',
  NumFeInjure = 'NumFeInjure',
  NumKidInjure = 'NumKidInjure',
  NumOldInjure = 'NumOldInjure',
  NumDisInjure = 'NumDisInjure',
  NumFamEva = 'NumFamEva',
  NumPeoEva = 'NumPeoEva',
  NumMeEva = 'NumMeEva',
  NumFeEva = 'NumFeEva',
  NumKidEva = 'NumKidEva',
  NumOldEva = 'NumOldEva',
  NumDisEva = 'NumDisEva',
  NumFamRe = 'NumFamRe',
  NumPeoRe = 'NumPeoRe',
  NumMeRe = 'NumMeRe',
  NumFeRe = 'NumFeRe',
  NumKidRe = 'NumKidRe',
  NumOldRe = 'NumOldRe',
  NumDisRe = 'NumDisRe',
  PartlyBurn = 'PartlyBurn',
  CompletBurn = 'CompletBurn',
  SchAff = 'SchAff',
  SchDam = 'SchDam',
  HealthAff = 'HealthAff',
  HealthDam = 'HealthDam',
  RivBreakLo = 'RivBreakLo',
  RivBreakWid = 'RivBreakWid',
  NationalRod = 'NationalRod',
  RuralRoad = 'RuralRoad',
  Bridge = 'Bridge',
  PagoAff = 'PagoAff',
  PagoDam = 'PagoDam',
  BuildingAff = 'BuildingAff',
  BuildingDam = 'BuildingDam',
  MarketAff = 'MarketAff',
  MarketDam = 'MarketDam',
  StorageAff = 'StorageAff',
  StorageDam = 'StorageDam',
  CraftAff = 'CraftAff',
  CraftDam = 'CraftDam',
  CropAff = 'CropAff',
  CropDam = 'CropDam',
  integer_ws0la67 = 'integer_ws0la67',
  integer_da9ns07 = 'integer_da9ns07',
  SamnabAff = 'SamnabAff',
  SamnabDam = 'SamnabDam',
  PaddyAff = 'PaddyAff',
  PaddyDam = 'PaddyDam',
  CowDeath = 'CowDeath',
  BaffoDeath = 'BaffoDeath',
  PigDeath = 'PigDeath',
  ChickDeath = 'ChickDeath',
  NumJungleAf = 'NumJungleAf',
  FarmAf = 'FarmAf',
}

export const incidentSpecificKeys = {
  [IncidentSpecific.NumVillAff]: 'group_tc1fy38/group_pf1pd97/NumVillAff',
  [IncidentSpecific.NumFamAff]: 'group_tc1fy38/group_pf1pd97/NumFamAff',
  [IncidentSpecific.NumPeoAff]: 'group_tc1fy38/group_pf1pd97/NumPeoAff',
  [IncidentSpecific.NumFeAff]: 'group_tc1fy38/group_pf1pd97/NumFeAff',
  [IncidentSpecific.NumDeathTo]: 'group_tc1fy38/group_bz3jq33/NumDeathTo',
  [IncidentSpecific.NumMeDeath]: 'group_tc1fy38/group_bz3jq33/NumMeDeath',
  [IncidentSpecific.NumFeDeath]: 'group_tc1fy38/group_bz3jq33/NumFeDeath',
  [IncidentSpecific.NumKidDeath]: 'group_tc1fy38/group_bz3jq33/NumKidDeath',
  [IncidentSpecific.NumOldDeath]: 'group_tc1fy38/group_bz3jq33/NumOldDeath',
  [IncidentSpecific.NumDisDeath]: 'group_tc1fy38/group_bz3jq33/NumDisDeath',
  [IncidentSpecific.ToNumMising]: 'group_tc1fy38/group_th37h10/ToNumMising',
  [IncidentSpecific.NumMeMising]: 'group_tc1fy38/group_th37h10/NumMeMising',
  [IncidentSpecific.NumFeMising]: 'group_tc1fy38/group_th37h10/NumFeMising',
  [IncidentSpecific.NumKidMising]: 'group_tc1fy38/group_th37h10/NumKidMising',
  [IncidentSpecific.NumOldMising]: 'group_tc1fy38/group_th37h10/NumOldMising',
  [IncidentSpecific.NumDisMising]: 'group_tc1fy38/group_th37h10/NumDisMising',
  [IncidentSpecific.ToNumInjure]: 'group_tc1fy38/group_sa7hz27/ToNumInjure',
  [IncidentSpecific.NumMeInjure]: 'group_tc1fy38/group_sa7hz27/NumMeInjure',
  [IncidentSpecific.NumFeInjure]: 'group_tc1fy38/group_sa7hz27/NumFeInjure',
  [IncidentSpecific.NumKidInjure]: 'group_tc1fy38/group_sa7hz27/NumKidInjure',
  [IncidentSpecific.NumOldInjure]: 'group_tc1fy38/group_sa7hz27/NumOldInjure',
  [IncidentSpecific.NumDisInjure]: 'group_tc1fy38/group_sa7hz27/NumDisInjure',
  [IncidentSpecific.NumFamEva]: 'group_tc1fy38/group_sg8yl06/NumFamEva',
  [IncidentSpecific.NumPeoEva]: 'group_tc1fy38/group_sg8yl06/NumPeoEva',
  [IncidentSpecific.NumMeEva]: 'group_tc1fy38/group_sg8yl06/NumMeEva',
  [IncidentSpecific.NumFeEva]: 'group_tc1fy38/group_sg8yl06/NumFeEva',
  [IncidentSpecific.NumKidEva]: 'group_tc1fy38/group_sg8yl06/NumKidEva',
  [IncidentSpecific.NumOldEva]: 'group_tc1fy38/group_sg8yl06/NumOldEva',
  [IncidentSpecific.NumDisEva]: 'group_tc1fy38/group_sg8yl06/NumDisEva',
  [IncidentSpecific.NumFamRe]: 'group_tc1fy38/group_mq8uz76/NumFamRe',
  [IncidentSpecific.NumPeoRe]: 'group_tc1fy38/group_mq8uz76/NumPeoRe',
  [IncidentSpecific.NumMeRe]: 'group_tc1fy38/group_mq8uz76/NumMeRe',
  [IncidentSpecific.NumFeRe]: 'group_tc1fy38/group_mq8uz76/NumFeRe',
  [IncidentSpecific.NumKidRe]: 'group_tc1fy38/group_mq8uz76/NumKidRe',
  [IncidentSpecific.NumOldRe]: 'group_tc1fy38/group_mq8uz76/NumOldRe',
  [IncidentSpecific.NumDisRe]: 'group_tc1fy38/group_mq8uz76/NumDisRe',
  [IncidentSpecific.PartlyBurn]: 'group_fh3jp70/group_cn0sw74/PartlyBurn',
  [IncidentSpecific.CompletBurn]: 'group_fh3jp70/group_cn0sw74/CompletBurn',
  [IncidentSpecific.SchAff]: 'group_fh3jp70/group_ez5mr58/SchAff',
  [IncidentSpecific.SchDam]: 'group_fh3jp70/group_ez5mr58/SchDam',
  [IncidentSpecific.HealthAff]: 'group_fh3jp70/group_bj6tu99/HealthAff',
  [IncidentSpecific.HealthDam]: 'group_fh3jp70/group_bj6tu99/HealthDam',
  [IncidentSpecific.RivBreakLo]: 'group_fh3jp70/group_pv8hz72/RivBreakLo',
  [IncidentSpecific.RivBreakWid]: 'group_fh3jp70/group_pv8hz72/RivBreakWid',
  [IncidentSpecific.NationalRod]: 'group_fh3jp70/group_pv8hz72/NationalRod',
  [IncidentSpecific.RuralRoad]: 'group_fh3jp70/group_pv8hz72/RuralRoad',
  [IncidentSpecific.Bridge]: 'group_fh3jp70/group_pv8hz72/Bridge',
  [IncidentSpecific.PagoAff]: 'group_pk03i04/group_wa9cj38/PagoAff',
  [IncidentSpecific.PagoDam]: 'group_pk03i04/group_wa9cj38/PagoDam',
  [IncidentSpecific.BuildingAff]: 'group_pk03i04/group_fg5ko43/BuildingAff',
  [IncidentSpecific.BuildingDam]: 'group_pk03i04/group_fg5ko43/BuildingDam',
  [IncidentSpecific.MarketAff]: 'group_pk03i04/group_hi74i16/MarketAff',
  [IncidentSpecific.MarketDam]: 'group_pk03i04/group_hi74i16/MarketDam',
  [IncidentSpecific.StorageAff]: 'group_pk03i04/group_lf9ou90/StorageAff',
  [IncidentSpecific.StorageDam]: 'group_pk03i04/group_lf9ou90/StorageDam',
  [IncidentSpecific.CraftAff]: 'group_pk03i04/group_ub2hp14/CraftAff',
  [IncidentSpecific.CraftDam]: 'group_pk03i04/group_ub2hp14/CraftDam',
  [IncidentSpecific.CropAff]: 'group_gh6ag70/group_na4yi04/CropAff',
  [IncidentSpecific.CropDam]: 'group_gh6ag70/group_na4yi04/CropDam',
  [IncidentSpecific.integer_ws0la67]: 'group_gh6ag70/group_az7bv13/integer_ws0la67',
  [IncidentSpecific.integer_da9ns07]: 'group_gh6ag70/group_az7bv13/integer_da9ns07',
  [IncidentSpecific.SamnabAff]: 'group_gh6ag70/group_yh83p68/SamnabAff',
  [IncidentSpecific.SamnabDam]: 'group_gh6ag70/group_yh83p68/SamnabDam',
  [IncidentSpecific.PaddyAff]: 'group_gh6ag70/group_en38q31/PaddyAff',
  [IncidentSpecific.PaddyDam]: 'group_gh6ag70/group_en38q31/PaddyDam',
  [IncidentSpecific.CowDeath]: 'group_gh6ag70/group_wb0mf29/CowDeath',
  [IncidentSpecific.BaffoDeath]: 'group_gh6ag70/group_wb0mf29/BaffoDeath',
  [IncidentSpecific.PigDeath]: 'group_gh6ag70/group_wb0mf29/PigDeath',
  [IncidentSpecific.ChickDeath]: 'group_gh6ag70/group_wb0mf29/ChickDeath',
  [IncidentSpecific.NumJungleAf]: 'group_gh6ag70/group_gu1xp89/NumJungleAf',
  [IncidentSpecific.FarmAf]: 'group_gh6ag70/group_gu1xp89/FarmAf',
} as const;
